project:
  output-dir: _slides

format:
  revealjs: 
    theme: 
      - presentation.scss
      - htmlslides.scss
    fragments: false
    title-slide-attributes: 
      data-background-color: black
    include-after-body:
      - revealjs_titlepage_bgcolor.html
revealjs-plugins:
  - animate
  - revealCustomControls


statslogo: "logo_black.png"
semestercolor: "#b0f1ff"