project:
  type: book  


book:
  title: "Statistik 1"
  subtitle: "Wintersemester 2023/24"
  author: "Prof. Matthias Guggenmos"
  cover-image: images/logo.png
  search: true
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    logo: "images/logo.png"

  chapters:
    - index.qmd
    - part: "Vorlesung 01: Intro"
      chapters:
        - 01_intro/index.qmd
    - part: "Vorlesung 02: Messen in der Psychologie"
      chapters:
        - 02_messen/index.qmd
    - part: "Vorlesung 03: Lage- und Streuungsmaße"
      chapters:
        - 03_location_dispersion/index.qmd
    - part: "Vorlesung 04: Verteilungen"
      chapters:
        - 03_location_dispersion/index.qmd
    - part: "Vorlesung 05: Korrelation"
      chapters:
        - 04_correlation/index.qmd
    - part: "Vorlesung 06: Regression"
      chapters:
        - 05_regression/index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, style.css]
    number-depth: 1
    filters:
      - filters/pdf/color-text.lua
  pdf:
    documentclass: scrreprt
    # classoption: [twocolumn, landscape]
    # variant: "+mark"
    filters:
      - filters/pdf/color-text.lua
    geometry:
      - top=10mm
      - left=20mm
      - heightrounded
    colorlinks: true 
    include-in-header: 
      - text: |
          \usepackage{soul}
      - file: custom.tex
