---
title: "Übung 10: Konfidenzintervalle"
---

<!----------------->
<!---- Aufgabe ---->
<!----------------->
# Aufgabe

In einer Studie zu therapieresistenter Depression wird ein neuartiger Ansatz mit einem Psychedelikum untersucht. Die Interventionsgruppe ($\text{int}$; N=14) erhält das Psychedelikum, die Kontrollgruppe ($\text{ctr}$; N=18) ein Placebopräparat. Der Behandlungserfolg wird in beiden Gruppen mit einem Heilungsindex $X$ gemessen:

$$
\bar{x}_\text{int} = 1.6,\quad \hat{\sigma}_\text{int} = 0.5
$$

$$
\bar{x}_\text{ctr} = 1.5,\quad \hat{\sigma}_\text{ctr} = 0.4
$$

Der Unterschied im Behandlungserfolg beträgt also $\Delta\bar{x}=0.1$. Wie lautet das 95%-Konfidenzintervall und lässt das Intervall auf einen signifikanten Gruppenunterschied schließen?

::: {.callout-tip collapse=true title="Lösung"}

Formel Konfidenzintervall:

$$
CI_{95} = \hat{\theta}\pm t_{(1-\frac{\alpha}{2},\;\text{df})}\cdot\hat{se}\qquad\text{Hinweis:}\;\hat{\theta} = \Delta\bar{x}
$$

Für den kritischen t-Wert wird die Zahl der Freiheitsgrade benötigt. Für unabhängige Stichproben und ähnliche Varianzen (Verhältnis kleiner 2) gilt:

$$
\text{df} = n_\text{int} + n_\text{ctr} - 2 = 14 + 18 - 2 = 30
$$

Somit lässt sich der kritische t-Wert der t-Tabelle entnehmen (Fläche 0.975):
$$
t_{(1-\frac{\alpha}{2},\;\text{df})} = t_{(0.975,\;30)} = 2.042
$$

Der Standardfehler bei unabhängigen Stichproben berechnet sich zu:

$$
\hat{se} = \hat{\sigma}_\text{pooled}\sqrt{\frac{1}{n_\text{int}}+\frac{1}{n_\text{ctr}}} = \hat{\sigma}_\text{pooled}\sqrt{\frac{1}{14}+\frac{1}{18}} = 0.356\cdot\hat{\sigma}_\text{pooled}
$$

$$
\begin{aligned}
\hat{\sigma}_\text{pooled} &= \sqrt{\frac{(n_\text{int}-1)\hat{\sigma}^2_\text{int} + (n_\text{ctr}-1)\hat{\sigma}^2_\text{ctr}}{n_\text{int}+n_\text{ctr}-2}} = \sqrt{\frac{(14-1)\cdot 0.5^2 + (18-1)\cdot 0.4^2}{14+18-2}} = \\
&= \sqrt{\frac{13\cdot 0.25 + 17\cdot 0.16}{30}} = \sqrt{\frac{5.97}{30}} = 0.446
\end{aligned}
$$

$$
\hat{se} = 0.356\cdot\hat{\sigma}_\text{pooled} = 0.356\cdot0.446 = 0.159
$$

Damit lautet das Konfidenzintervall:

$$
CI_{95} = \hat{\theta}\pm t_{(1-\frac{\alpha}{2},\;\text{df})}\cdot\hat{se} = 0.1 \pm 2.042\cdot 0.159 = 0.1 \pm 0.325
$$

Intervalldarstellung:

$$
CI_{95} = [-0.225; 0.425]
$$

Das Konfidenzintervall enthält also die $0$ &mdash; der Gruppenunterschied ist **nicht signifikant**.

:::




<!----------------->
<!---- Aufgabe ---->
<!----------------->
# Aufgabe

In besagter Studie untersuchen Sie innerhalb der Interventionsgruppe den Zusammenhang von Offenheit gegenüber Psychedelika $Y$ und Heilungsindex $X$. Sie erhalten eine Korrelation von $\hat{\rho}=0.3$. Bestimmen Sie das 95%-Konfidenzintervall im Korrelationsraum und treffen Sie eine Aussage zur Signifikanz des Zusammenhangs.

::: {.callout-tip collapse=true title="Lösung"}

1. Fisher Z-Transformation

$$
Z = \text{artanh}\left(\hat{\rho}\right) = \text{artanh}\left(0.3\right)\overset{\text{(Fisher Z-Tabelle)}}{=}0.31
$$

2. Berechnung des Konfidenzintervalls

$$
CI_Z=Z\pm z_{(1-\frac{\alpha}{2})}\cdot \hat{se}\qquad\text{mit}\quad \hat{se}=\frac{1}{\sqrt{n_\text{int}-3}}==\frac{1}{\sqrt{14-3}}=0.30
$$

Der kritische z-Wert für ein Konfidenzniveau von 0.95 entspricht dem z-Wert der eine Fläche von 0.975 abschneidet (Konfidenzniveau impliziert immer eine *zweiseitige* Testung):
$$
z_{(1-\frac{\alpha}{2})}=z_{(0.975)}=1.96
$$

Damit gilt: 

$$
CI_Z=0.31\pm 1.96\cdot 0.30=0.31\pm 0.588\qquad\text{bzw.}\quad CI_Z=[-0.278; 0.898]
$$

3. Rücktransformation in den Korrelationsraum

$$
CI = [\tanh{(Z^{u})}; \tanh{(Z^{o})}] = [\tanh{(-0.278)}; \tanh{(0.898)}] = [-0.271; 0.715]
$$

Da das Konfidenzintervall den Wert $0$ einschließt, ist die Korrelation nicht signifikant.


:::