---
title: "Quiz 00: Abi-Check"
---

# Quizfrage

Was ist der Mittelwert von $\{1, 2, 4, 7, 11\}$?

:::{.choices}
<input type="radio" name="avg1">2<br>
<input type="radio" name="avg1">3<br>
<input type="radio" name="avg1">5<br>
<input type="radio" name="avg1">7<br>
:::

::: {.callout-tip collapse=true title="Lösung"}
<input type="radio" name="avg1_s">2<br>
<input type="radio" name="avg1_s">3<br>
<input type="radio" name="avg1_s" checked>**5**<br>
<input type="radio" name="avg1_s">7<br>
:::

# Quizfrage

Was ist der Mittelwert von $\{-1746, -24, 0, 24, 1746\}$?

:::{.choices}
<input type="radio" name="avg2">$-1$<br>
<input type="radio" name="avg2">$0$<br>
<input type="radio" name="avg2">$1$<br>
<input type="radio" name="avg2">$1746$<br>
:::

::: {.callout-tip collapse=true title="Lösung"}
<input type="radio" name="avg2_s">$-1$<br>
<input type="radio" name="avg2_s" checked>$0$<br>
<input type="radio" name="avg2_s">$1$<br>
<input type="radio" name="avg2_s">$1746$<br>
:::



<!----------------->
<!---- Aufgabe ---->
<!----------------->
# Quizfrage

Was versteht man unter Stochastik?

<label class="checkbox-container"><input type="radio" name="sto">
    Ein mathematisches Teilgebiet, das sich mit Zufallsprozessen und Wahrscheinlichkeiten beschäftigt.
</label>
<label class="checkbox-container"><input type="radio" name="sto">
    Ein mathematisches Teilgebiet, das sich mit Infinitesimalrechnung beschäftigt.
</label>
<label class="checkbox-container"><input type="radio" name="sto">
    Ein mathematisches Teilgebiet, das sich mit linearer Algebra beschäftigt.
</label>
<label class="checkbox-container"><input type="radio" name="sto">
    Ein mathematisches Teilgebiet, das sich mit Geometrie beschäftigt.
</label>

::: {.callout-tip collapse=true title="Lösung"}
<label class="checkbox-container"><input type="radio" name="sto_s" checked>
    **Ein mathematisches Teilgebiet, das sich mit Zufallsprozessen und Wahrscheinlichkeiten beschäftigt.**
</label>
<label class="checkbox-container"><input type="radio" name="sto_s">
    Ein mathematisches Teilgebiet, das sich mit Infinitesimalrechnung beschäftigt.
</label>
<label class="checkbox-container"><input type="radio" name="sto_s">
    Ein mathematisches Teilgebiet, das sich mit linearer Algebra beschäftigt.
</label>
<label class="checkbox-container"><input type="radio" name="sto_s">
    Ein mathematisches Teilgebiet, das sich mit Geometrie beschäftigt.
</label>
:::



<!----------------->
<!---- Aufgabe ---->
<!----------------->
# Quizfrage

Wie hoch ist die Wahrscheinlichkeit, dass eine Münze drei mal in Folge Kopf zeigt?

:::{.choices}
<input type="radio" name="coin">$3$<br>
<input type="radio" name="coin" style="margin-top: 10px">$\frac{1}{2}$<br>
<input type="radio" name="coin" style="margin-top: 10px">$\frac{1}{4}$<br>
<input type="radio" name="coin" style="margin-top: 10px">$\frac{1}{8}$<br>
:::

::: {.callout-tip collapse=true title="Lösung"}
<input type="radio" name="coin_s">$3$<br>
<input type="radio" name="coin_s" style="margin-top: 10px">$\frac{1}{2}$<br>
<input type="radio" name="coin_s" style="margin-top: 10px">$\frac{1}{4}$<br>
<input type="radio" name="coin_s" checked style="margin-top: 10px">$\mathbf{\frac{1}{8}}$<br>
:::



<!----------------->
<!---- Aufgabe ---->
<!----------------->
# Quizfrage

Welcher Schlussfolgerungsprozess beginnt mit spezifischen Beobachtungen und leitet daraus allgemeine Prinzipien ab?

:::{.choices}
<input type="radio" name="ind">Deduktion<br>
<input type="radio" name="ind">Abduktion<br>
<input type="radio" name="ind">Indukion<br>
<input type="radio" name="ind">Reduktion<br>
:::

::: {.callout-tip collapse=true title="Lösung"}
<input type="radio" name="ind_s">Deduktion<br>
<input type="radio" name="ind_s">Abduktion<br>
<input type="radio" name="ind_s" checked>**Indukion**<br>
<input type="radio" name="ind_s">Reduktion<br>
:::